export const ADD_PARENT_INPUT = "ADD_PARENT_INPUT";
export const ADD_CHILD_INPUT = "ADD_CHILD_INPUT";
export const EDIT_PARENT_INPUT = "EDIT_PARENT_INPUT";
export const EDIT_CHILD_INPUT = "EDIT_CHILD_INPUT";
export const DELETE_CHILD_INPUT = "DELETE_CHILD_INPUT";
export const DELETE_TASK = "DELETE_TASK";
